[build]
  command = "npm run build:client" # <-- CHANGE THIS LINE
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
